
title: Simple screen recorder
author: Adrian Mache
email: andi146@photonemail.com
description: > # this means to ignore newlines until "baseurl:"
  personal project dev log
# social links
twitter_username: Adrian # DO NOT include the @ character, or else the build will fail!
github_username:  Andi-146 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
